### ISSUE TITLE
nbteditor compress files on save in anyway

### ISSUE THREAD

**Issue by NiTiSon** [steelswing/nbteditor#1]
### Reproduse:
1. Open (not-compressed) `file.nbt` by nbteditor
1. Save `file.nbt` by nbteditor
#### Result: 
Now `file.nbt` compressed by gzip 😭 

### Resolution:
+ Compress only those nbt files that been compressed
`OR`
+ Ask user if file should be compressed + (compress level option)

**Comment by steelswing** [comment]
Added in release 1.3
https://github.com/steelswing/nbteditor/releases/tag/1.3
